---
- hosts: all
  remote_user: gmkbabu
  become: yes
  tasks:
   - name: download the java
     get_url: url=http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz dest=/tmp/
  
   - name: create the java folder
     command: mkdir /usr/local/java state=directory
  
   - name: unpack the java
     unarchive: src=/tmp/jdk-8u131-linux-x64.tar.gz dest=/usr/local/java copy=no 
  
   - name: set the java home
     lineinfile: dest=~/.bashrc regexp='<JAVA_HOME>'
              line="export JAVA_HOME=/usr/local/java/jdk1.8.0_131"
             
   - name: set the java path
     lineinfile: dest=~/.bashrc regexp='<JAVA_HOME>'
                line='export PATH="$PATH:$JAVA_HOME/bin"'
                
   - name: source bashrc
     shell: source ~/.bashrc            